### ISSUE TITLE
Add command to roll-back a single block

### ISSUE THREAD

**Issue by AdityaSripal** [tendermint/tendermint#3845]
Many times, a full node panics on Consensus failure due to a mismatch in the expected and actual `AppHash`. This is often caused by misconfiguration or running the wrong versions of software on the part of the full node, rather than a malicious validator set.

Currently the only solution I know of is to reset the data, fix the issue, then start over.

However it is possible for the node to get a mismatch after doing a lot of syncing. In this case, the node will panic on the first block for which it sees an app-hash mismatch.

Rather than resetting the data and undoing a lot of valid syncing, tendermint should allow the ability to rollback a single block's execution. This would allow the full node operator to diagnose the issue, fix it, and continue syncing from where it left off rather than having to start over.

The ability to Rollback a version is already available on IAVL, so rolling back app-state is not an issue. We would just need to add functionality to rollback rest of Tendermint State as well if that doesn't already exist, and create a cli command to do it.

If this feature already exists, it would be very useful to be pointed to the code where it is implemented.

**Comment by ebuchman** [comment]
So it seems this might be simpler to fix than so far anticipated, assuming the latest committed block is correct, but the app hash computed from it is incorrect on less than 1/3 of the validators.

In this case, it should be possible to just rollback the app one height, fix things there, and restart tendermint. Tendermint will replay the latest block (which is itself correct), and give the app the chance to return the correct app hash.

Only now, the correct app hash returned from the app will differ from the one stored by Tendermint the last time the block was executed, and the replay mechanism will fail: https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L450

So it seems we might only need some way to let the app over ride the latest app hash stored by tendermint, rather than actually rolling anything back at the tendermint level.

Of course this also assumes the changes to the app won't impact the app hash from previous blocks.

Would this be sufficient to address this issue? Or is there some more pathological case ?

**Comment by AdityaSripal** [comment]
Ah I see, yea i think that should solve the specific problem I have above. I'm not sure if there are any other situations where users might want to roll-back TM blocks.

Is there any danger in not having the check to make sure the new replayed app-hash equals the old app-hash?

**Comment by tessr** [comment]
@AdityaSripal Is this something you're still interested in?

**Comment by AdityaSripal** [comment]
No I believe Ethan's suggestion is sufficient. You may close this. Thanks!

**Comment by sunnya97** [comment]
Is there an issue for @ebuchman's solution?

**Comment by cmwaters** [comment]
Was talking to Marko about this and we agreed that this has not yet been resolved. The problem that remains is that although the block itself is correct, Tendermint's last state it saved has the incorrect hash. Thus when a node restarts Tendermint, it will still have the incorrect AppHash. What we need to do is to allow for the last state to be removed and to execute the last block against the app again.
There are two approaches to signalling a rollback to happen:
1. The application initiates it in the handshake: i.e. `Info` returns a boolean that indicates whether to roll back tendermint state back to the applications height.
2. The node operator manually does it via an offline cli command that clips the last saved state from the state store

**Reconstructing State**
Note that Tendermint doesn't save states directly but will need to be able to derive it from a combination of the previous block + consensus params + validator sets

**CosmosSDK / Application side work**
The CosmosSDK or application will also need to add some tooling that allows a node to revert to the previous state

cc @marbar3778  - I'll assign myself to this :)

**Comment by ethanfrey** [comment]
Hey @cmwaters I was just looking at a case when I need to rollback state one block for a post-mortem. And Aditya kindly pointed out this issue. From the long past...

> In this case, it should be possible to just rollback the app one height, fix things there, and restart tendermint. Tendermint will replay the latest block (which is itself correct), and give the app the chance to return the correct app hash.

"just" is funny, as this was the tooling I was thinking I would have to build (that doesn't exist in the ecosystem).

> Only now, the correct app hash returned from the app will differ from the one stored by Tendermint the last time the block was executed, and the replay mechanism will fail

Is this still true? I assume you are looking into this part?

There are two parts.
1. "Just" rolling back the app state one block
2. Tendermint accepting this replayed block to overwrite it's state
I feel competent to tackle (1). Not sure about (2) and really don't want to get into forking tendermint.

I would love an update on the state of that.

**Comment by cmwaters** [comment]
> Is this still true? I assume you are looking into this part?

Yup, I'm still planning on doing this work. Is there a preference towards which approach I take (i.e. to modify ABCI or add a CLI command). In the case of modifying ABCI, I might be tempted to pair this with the ABCI++ breaking changes so this feature wouldn't be around until 0.36. It could also be possible to setup a temporary cli as an intermediate work around if the feature is relatively important.

**Comment by ethanfrey** [comment]
This whole rollback process I only see as useful as a cli for manual intervention. Either to do a post mortem on AppHash mismatch, or to rollback one block when you fail to halt a node for an upgrade.

The use cases for an app to trigger this are much fewer.

Any chance such a tool would be available for the 0.34.x line anytime soon?
